clickstorm/cs_seo

- Classes/Hook/PageHook.php
fix 404 error of typo3 assets if typo3 lives in a subfolder
> correct assets paths

- Classes/UserFunc/StructuredData.php
- Configuration/TypoScript/Setup/meta.ts
- Configuration/TypoScript/Setup/plugin.ts
- Configuration/TypoScript/Setup/structuredData.ts
- Configuration/TypoScript/constants.txt
- Configuration/TypoScript/setup.txt
@see https://developers.google.com/search/docs/guides/intro-structured-data
- Added ts-options to enable both (sitesearch and breadcrumb) Independently of each other
- Added Userfunc to add the json-ld data to the footer of the page
> [FEATURE] support for google structured data (siteSearch and Breadcrumb)

- Classes/UserFunc/StructuredData.php
- Configuration/TypoScript/Setup/structuredData.ts
Checking tmpl->flatSetup while rendering the page (and generating hash for caching) returns different values. While rendering the page, flatSetup is not present. While rendering C-Objects, flatSetup is available. So during the complete rendering process, the function returns different values and therefore the page would never ever beeing cachable.
As this functions are used system wide, the complete website would not be cachable.
> [BUGFIX] Usage of tmpl->flatSetup prevents page from beeing cachable

- ext_localconf.php
If you have enabled cs_seo in `PackageStates.php` during TYPO3 install the database setup will fail because it tries to access the pages table (pageTSConfig) in the TCA extends hook.
The fix is simply taken from `flux` and disables all ext_localconf stuff while TYPO3 is installing.
> [BUGFIX] Don't run any hooks during TYPO3 install

- Configuration/TypoScript/Setup/Meta/twitterCards.ts
As shown here: https://dev.twitter.com/cards/types/summary-large-image
> [BUG] twitter:image is a name not a property

- Classes/UserFunc/Sitemap.php
- Configuration/TypoScript/Extensions/News/setup.txt
I had an issue with wrong url creation in conjunction with the extension realurl. Basically cs_seo generated urls without a cHash parameter which resulted in wrong mappings in realurl.
> [FEATURE] add useCacheHash as option in sitemap for extension

- Documentation/Configuration/Sitemap/Index.rst
> [BUGFIX] Use correct property in documentation for doktypes

- Classes/UserFunc/HeaderData.php
When a fallback is defined on a model for og_image/tw_image, and if cs_seo IRRE-record exists,
a php error was thrown: #1316789798: UID of related record has to be an integer. UID given: ""
This commit fixes that issue by using the right uid (record's uid) when loading the image file.
Fixes #92
> [BUGFIX] Fix og_image fallback when no cs_seo IRRE-record exists

- Configuration/TypoScript/PageTypes/robotsTxt-656.ts
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | -
| Related issues/PRs | -
| License | GPL-2.0+
Fixes the TypoScript configuration of the Content-Type header for the robots.txt page type. According to the TypoScript documentation, `config.additionalHeaders` must be an array. Without this, the robots.txt is sent as `text/html`.
- https://docs.typo3.org/typo3cms/TyposcriptReference/7.6/Setup/Config/#additionalheaders
- https://docs.typo3.org/typo3cms/TyposcriptReference/8.7/Setup/Config/#additionalheaders
- https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/#additionalheaders
> [BUGFIX] Content-Type header for robots.txt

- Configuration/TypoScript/Setup/Tracking/googleAnalytics.ts
Hey,
the current wrap uses the split character two times which is not supported. Since two script tags are the output I gave each script tag its own TEXT object with a wrap.
all the best,
Jonathan
> Fixing typoscript wrap bug for Google Analytics

- Classes/Form/Element/SnippetPreview.php
Typo3: 8.7.14
cs_seo : dev-master
In production mode, the Wizard.css stylesheet is not loaded correctly. In development mode everything is fine. 
The problems seems to be that in `SnippetPreview->loadCss()` you create an absolute path for the stylesheet that is not supported by `ResourceCompressor->compressCssFile()`. Changing to a relative path seems to fix the issue on my side.
> [BUGFIX] Backend styles not loading in production

- Classes/UserFunc/PageTitle.php
This is related to #162
I added the fallback to altPageTitle if no explicit seo_title is defined.
This will allow news or other extensions to define their own title.
> add altPageTitle fallback

- Classes/Hook/MetaTagGeneratorHook.php
When config.locale_all contains charset (ie. fr_FR.UTF-8), og:locale is malformed.
Facebook Open Graph debugger says it is not a valid enum.
This commit removes the charset part of config.locale_all from og:locale.
Fixes #221
> [BUGFIX] Fix og:locale in case of config.locale_all contains charset

- Classes/UserFunc/StructuredData.php
This fixes two current issues:
1.  TYPO3\CMS\Frontend\Page\PageRepository->getRootLine() is deprecated since TYPO3 9.4
(see [https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85557-PageRepository-getRootLine.html](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85557-PageRepository-getRootLine.html))
2. Folders are included in the breadcrumb instead of being skipped similar to HMENU
> [BUGFIX] remove deprecated getRootline and skip folders in breadcrumb

- Classes/Command/EvaluationCommandController.php
- Classes/Controller/ModuleController.php
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5/Deprecation-84196-BackendControllerActionsDoNotReceivePreparedResponse.html and Issue #250
> [TASK] Fix Deprecation #84196, resolves Issue #250

- Classes/Controller/ModuleController.php
HTMLResponse must not be invoked without the content parameter, as reported in https://github.com/clickstorm/cs_seo/issues/244#issuecomment-539313788
> [BUGFIX] Fix Regression of #251

- Classes/Utility/TSFEUtility.php
For some reason the TSFE->cObj is empty when submitting a tx_forms form which leads to the error message "Call to a member function stdWrap() on string" even though the forms action is executed successfully.
> [BUGFIX] fix Call to a member function stdWrap() on string error

- Classes/Service/Backend/GridService.php
This commit fixes every BE module except for the "SEO" one. Due to a
typo in the Context configuration the values for each page are always
from the default language. The "SEO" module action works as the
Context is already created in the controller action by creating a
TSFE object.
> [BUGFIX] fix localization for most BE modules

- Classes/UserFunc/PageTitle.php
Branch `6x` is targeted for TYPO3 v10 which had a minimum requirement of PHP 7.2. Using class properties requires at least PHP 7.4 and fails in any earlier version.
Related: 66b9253
Fixes: #301
> [BUGFIX] Avoid using typed class properties

- Classes/Service/Backend/GridService.php
- Resources/Private/Language/de.locallang_csh_meta.xlf
- Resources/Private/Language/de.locallang_csh_pages.xlf
- Resources/Private/Language/locallang_csh_meta.xlf
- Resources/Private/Language/locallang_csh_pages.xlf
This bugfix fixes inconsistent labels for the checkboxes no_index and no_follow that since they were moved to the seo extension with TYPO3 9.  Thereby their values have reversed (for whatever reason).
This circumstance still leads to incorrect statements, e.g. in csh labels.
Also the icons in the SEO module show since then inverted states.
> [BUGFIX] Labels of noindex nofollow fields and grid view icons

- Configuration/TCA/Overrides/pages.php
With auto-creation of TCA type 'input' fields introduced in TYPO3 13.2.0, the `max` property is now required to be of type int if present. Otherwise, a type error is thrown:
TypeError: Doctrine\DBAL\Schema\Column::setLength():
Argument #1 ($length) must be of type ?int, string given,
called in vendor/doctrine/dbal/src/Schema/Column.php on line 65
vendor/doctrine/dbal/src/Schema/Column.php:78
vendor/doctrine/dbal/src/Schema/Column.php:65
vendor/doctrine/dbal/src/Schema/Column.php:52
vendor/doctrine/dbal/src/Schema/Table.php:261
vendor/typo3/cms-core/Classes/Database/Schema/DefaultTcaSchema.php:784
vendor/typo3/cms-core/Classes/Database/Schema/DefaultTcaSchema.php:70
vendor/typo3/cms-core/Classes/Database/Schema/SchemaMigrator.php:433 …
> [BUGFIX] type error in 'max' with TYPO3 13.2.0
