clickstorm/cs_seo

Classes/Hook/PageHook.php
overwriting partials / using my own evaluation did only work for me in the backend module, not in page module... this should fix the problem
=> [BUGFIX] allow template / partial to be overwritten via TS

Classes/Service/FrontendPageService.php, Resources/Private/Layouts/Module.html, Resources/Private/Layouts/ModuleEvaluation.html
=> [BUGFIX] Fix missing commas in module layouts

Classes/Service/FrontendPageService.php
=> [BUGFIX] Ensure HTTP reponse 200 is accepted while fetching HTML content

Configuration/TypoScript/constants.txt
=> [TASK] Typo fix

Classes/UserFunc/HeaderData.php
https://github.com/clickstorm/cs_seo/issues/47
=> [BUGFIX] Resolve issue 47

Configuration/TCA/tx_csseo_domain_model_meta.php
- Because not available translation, the access tab was not shown
- Set language to default instead of all as default
Resolves: #63
=> [BUGFIX] Fix broken TCA for v1 in 8.6

Classes/UserFunc/StructuredData.php
Better handling for TSFE->MP variable.
=> [BUGFIX] Verify TSFE-MountPoint before use.

Classes/UserFunc/Sitemap.php
=> [BUGFIX] Respect useCacheHash configuration in extension sitemap

Classes/UserFunc/Sitemap.php, Documentation/Developer/ExtendSitemap/Index.rst
=> [FEATURE] Make it possible to fetch records for sitemap by UserFunction

Configuration/TypoScript/Extensions/News/constants.txt
=> [BUGFIX] Add missing sitemap.extensions.news.recursive constant

Resources/Public/JavaScript/jquery.cs_seo.ga.js
Location change breaks lightbox videos like youtube
=> [BUGFIX] Remove location change from jquery.cs_seo.ga.js

Configuration/TypoScript/Setup/Tracking/piwik.ts
Load the compressed version of piwik 
https://developer.piwik.org/api-reference/tracking-javascript#minify-piwikjs
=> [FEATURE] using compressed version of piwik

Configuration/TypoScript/Setup/Meta/openGraph.ts
The passed values where empty for me because I might not be using all your TS, but that was it always comes out of the constants
=> [BUGFIX] og:image read height/width directly from Contants

Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf
=> Change spelling

Classes/UserFunc/HeaderData.php
Backport of #235 for 3.x branch and TYPO3 8.7
=> [BUGFIX] Let TYPO3 manage the version and record overlays

Configuration/TypoScript/Setup/tracking.typoscript
https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Conditions/Index.html#frontend-user-isloggedin
=> [TASK] Simplify the backend.user condition

Classes/Utility/ConfigurationUtility.php
This code was borrowed from the master branch. The origin PR is this one here: https://github.com/clickstorm/cs_seo/pull/268
Issue regarding this bug: https://github.com/clickstorm/cs_seo/issues/274
Would be great if this could be merged and a new release tagged.
Thank you very much!
Best wishes
Tom
=> Check if site variable contains a Site and not a PseudoSite

Classes/Service/Backend/GridService.php, Resources/Public/JavaScript/Module/controllers/CsSeoController.js
* Use BE user language instead of requested page language
* Use language key instead of language int
=> [BUGFIX] Fix Grid UI localization

Classes/Service/HrefLangService.php
=> Remove superflous variable in HrefLangService

Classes/EventListener/AfterTcaCompilationEventListener.php
=> Keep TCA changes from other event listeners

Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_csh_mod.xlf, Resources/Private/Language/locallang_csh_pages.xlf, Resources/Private/Language/locallang_db.xlf
Please add suggested corrections in source strings
=> fix: various typos in language files

Resources/Private/Language/de.locallang_csh_pages.xlf, Resources/Private/Language/locallang_csh_pages.xlf
TYPO3 change commit: https://forge.typo3.org/projects/typo3cms-core/repository/1749/revisions/eade861a4aa878cfcf80c07e3eaa5b2a8a0665ec
=> [BUGFIX] #338 change no_follow description to their new inverted variant

Resources/Private/Partials/Module/GooglePreview.html, Resources/Private/Partials/Module/Grid.html
See https://github.com/clickstorm/cs_seo/issues/341
=> [BUGFIX] Add nonce to fix Content Security Policy errors.
